[tool.poetry]
name = "crl-checker"
version = "0.0.0"
description = "Check if certificate is revoked using the x509 CRL extension"
authors = ["Michal Sadowski <misad90@gmail.com>"]
license = "MIT"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Security :: Cryptography",
    "Operating System :: OS Independent"
]
readme = "README.md"
homepage = "https://github.com/fulder/crl-checker"
repository = "https://github.com/fulder/crl-checker"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/fulder/crl-checker/issues"

[tool.poetry.dependencies]
python = "^3.7"
cryptography = ">=39.0.1,<42.0.0"
requests = "^2.28.2"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest = "^7.2.1"
pytest-mock = "^3.10.0"
pytest-cov = "^4.0.0"

[tool.poetry.group.lint]
optional = true

[tool.poetry.group.lint.dependencies]
flake8 = { version = "^6.0.0", python = ">=3.8.1" }
black = "^23.1.0"
isort = { version = "^5.12.0", python = ">=3.8" }

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry_dynamic_versioning.backend"

[tool.isort]
profile = "black"

[tool.black]
line_length = 79

[tool.pytest.ini_options]
addopts = "--cov=crl_checker --cov-report term-missing --cov-report=html -v"
