name: Deploy docs

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6.0.3

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version-file: .python-version

      - name: Install uv
        run: pip install --require-hashes -r requirements.txt

      - name: Build site
        run: uv run --group docs mkdocs build

      - name: Deploy to gh-pages
        run: uv run --group docs mkdocs gh-deploy --force --config-file ./mkdocs.yml
